"""Regenerate docs/cli.md from live Click help output."""

from __future__ import annotations

import shutil
import subprocess
from pathlib import Path

SUBCOMMANDS = [
    "process",
    "batch",
    "aggregate",
    "plot",
    "pipeline",
    "compare-group",
    "plot-group",
    "connectivity",
    "qc-report",
    "bursts",
    "compare-baseline",
    "compare-conditions",
    "plot-raster",
    "plot-spatial",
]


def _run_help(command: list[str]) -> str:
    executable = shutil.which("meaorganoid")
    if executable is None:
        raise RuntimeError("meaorganoid executable was not found on PATH")
    result = subprocess.run(
        [executable, *command, "--help"],
        check=True,
        text=True,
        capture_output=True,
    )
    return result.stdout.rstrip()


def render_cli_docs() -> str:
    """Render the full CLI reference page.

    Parameters
    ----------
    None
        This helper takes no parameters.

    Returns
    -------
    str
        Markdown content for ``docs/cli.md``.

    Examples
    --------
    >>> "CLI Reference" in render_cli_docs()
    True
    """
    sections = [
        "# CLI Reference",
        "",
        (
            "This page is generated by `scripts/dev/regen_cli_docs.py` from live "
            "`meaorganoid --help` output."
        ),
        "",
        "## `meaorganoid`",
        "",
        "```text",
        _run_help([]),
        "```",
    ]
    for subcommand in SUBCOMMANDS:
        sections.extend(
            [
                "",
                f"## `meaorganoid {subcommand}`",
                "",
                "```text",
                _run_help([subcommand]),
                "```",
            ]
        )
    return "\n".join(sections) + "\n"


def main() -> None:
    """Write the generated CLI reference page.

    Parameters
    ----------
    None
        This command takes no parameters.

    Returns
    -------
    None
        Writes ``docs/cli.md`` in place.

    Examples
    --------
    >>> callable(main)
    True
    """
    Path("docs/cli.md").write_text(render_cli_docs(), encoding="utf-8")


if __name__ == "__main__":
    main()
